
export const CURRENCY_LIST_CACHE_KEY = "currencyListData";
export const CURRENCY_LIST_CACHE_DURATION = 60 * 60 * 1000;

export const MONEY_CHANGER_CURRENCIES_CACHE_KEY ="MONEY_CHANGER_CURRENCIES_CACHE_KEY";
export const MONEY_CHANGER_CURRENCIES_CACHE_DURATION = "MONEY_CHANGER_CURRENCIES_CACHE_DURATION";
